{"name": "Проверка получения заказов для авторизованного пользователя - нет заказов", "status": "failed", "statusDetails": {"message": "AssertionError: Получено неверное значение ключа \"total\": ожидалось \"0\", получено \"34893\"", "trace": "self = <test_get_user_orders.TestGetUserOrders object at 0x00000276DE027DD0>\n\n    @allure.title('Проверка получения заказов для авторизованного пользователя - нет заказов')\n    def test_get_user_orders_authorized_user_no_orders(self):\n        # получаем заказы пользователя\n        response = try_to_get_user_orders(self.auth_token)\n    \n        # Проверяем, что получен статус-код 200 OK и в теле ответа \"success\" = True\n        # и получаем тело ответа\n        received_body = check_success_ok(response)\n    \n        # проверяем поле \"orders\" и количество заказов\n        received_orders_list = check_received_orders_list(received_body, 0)\n    \n        # проверяем поля \"total\" и \"totalToday\" в теле ответа\n>       check_received_orders_info(received_body, 0)\n\ntests\\test_get_user_orders.py:116: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nhelpers\\helpers_on_check_response.py:209: in check_received_orders_info\n    check_key_and_value_in_body(received_body, KEYS.TOTAL_KEY, amount)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse_body = {'orders': [], 'success': True, 'total': 34893, 'totalToday': 116}, key = 'total', value = 0\n\n    @allure.step('Проверяем значение ключа в ответе')\n    def check_key_and_value_in_body(response_body, key, value):\n        # проверяем наличие ключа в ответе\n        assert key in response_body, f'В ответе отсутствует ключ \"{key}\", получен ответ: \"{response_body}\"'\n        # проверяем значение ключа в ответе\n        received_value = response_body[key]\n>       assert received_value == value, f'Получено неверное значение ключа \"{key}\": ожидалось \"{value}\", получено \"{received_value}\"'\nE       AssertionError: Получено неверное значение ключа \"total\": ожидалось \"0\", получено \"34893\"\n\nhelpers\\helpers_on_check_response.py:38: AssertionError"}, "steps": [{"name": "Отправляем запрос на получение заказов пользователя", "status": "passed", "steps": [{"name": "Отправляем API-запрос на получение заказов пользователя", "status": "passed", "parameters": [{"name": "headers", "value": "{'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWFmMzJmOWVkMjgwMDAxYjNhMWE3MCIsImlhdCI6MTcwNDY1MzYxNSwiZXhwIjoxNzA0NjU0ODE1fQ.3kPLr2cu9wx24j13mJS66KFVsoZT-NsZW8xy9A-TzWc'}"}], "start": 1704653615123, "stop": 1704653617098}], "parameters": [{"name": "auth_token", "value": "'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWFmMzJmOWVkMjgwMDAxYjNhMWE3MCIsImlhdCI6MTcwNDY1MzYxNSwiZXhwIjoxNzA0NjU0ODE1fQ.3kPLr2cu9wx24j13mJS66KFVsoZT-NsZW8xy9A-TzWc'"}], "start": 1704653615123, "stop": 1704653617098}, {"name": "Проверяем, что запрос выполнен успешно", "status": "passed", "steps": [{"name": "Проверяем код ответа", "status": "passed", "parameters": [{"name": "response", "value": "<Response [200]>"}, {"name": "expected_code", "value": "200"}], "start": 1704653617098, "stop": 1704653617098}, {"name": "Проверяем значение поля \"success\" в ответе", "status": "passed", "parameters": [{"name": "response", "value": "<Response [200]>"}, {"name": "expected_value", "value": "True"}], "start": 1704653617098, "stop": 1704653617098}], "parameters": [{"name": "response", "value": "<Response [200]>"}], "start": 1704653617098, "stop": 1704653617098}, {"name": "Проверяем в полученном ответе поле \"orders\" - список заказов", "status": "passed", "steps": [{"name": "Проверяем наличие ключа в ответе", "status": "passed", "parameters": [{"name": "response_body", "value": "{'success': True, 'orders': [], 'total': 34893, 'totalToday': 116}"}, {"name": "key", "value": "'orders'"}], "start": 1704653617098, "stop": 1704653617098}], "parameters": [{"name": "received_body", "value": "{'success': True, 'orders': [], 'total': 34893, 'totalToday': 116}"}, {"name": "amount", "value": "0"}], "start": 1704653617098, "stop": 1704653617098}, {"name": "Проверяем в полученном ответе поля \"total\" и \"totalToday\"", "status": "failed", "statusDetails": {"message": "AssertionError: Получено неверное значение ключа \"total\": ожидалось \"0\", получено \"34893\"\n", "trace": "  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\helpers\\helpers_on_check_response.py\", line 209, in check_received_orders_info\n    check_key_and_value_in_body(received_body, KEYS.TOTAL_KEY, amount)\n  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\helpers\\helpers_on_check_response.py\", line 38, in check_key_and_value_in_body\n    assert received_value == value, f'Получено неверное значение ключа \"{key}\": ожидалось \"{value}\", получено \"{received_value}\"'\n"}, "steps": [{"name": "Проверяем значение ключа в ответе", "status": "failed", "statusDetails": {"message": "AssertionError: Получено неверное значение ключа \"total\": ожидалось \"0\", получено \"34893\"\n", "trace": "  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\helpers\\helpers_on_check_response.py\", line 38, in check_key_and_value_in_body\n    assert received_value == value, f'Получено неверное значение ключа \"{key}\": ожидалось \"{value}\", получено \"{received_value}\"'\n"}, "parameters": [{"name": "response_body", "value": "{'success': True, 'orders': [], 'total': 34893, 'totalToday': 116}"}, {"name": "key", "value": "'total'"}, {"name": "value", "value": "0"}], "start": 1704653617099, "stop": 1704653617099}], "parameters": [{"name": "received_body", "value": "{'success': True, 'orders': [], 'total': 34893, 'totalToday': 116}"}, {"name": "amount", "value": "0"}], "start": 1704653617099, "stop": 1704653617099}], "attachments": [{"name": "stdout", "source": "e342295f-eb0c-4e00-918d-c519e248b4fb-attachment.txt", "type": "text/plain"}], "start": 1704653615123, "stop": 1704653617100, "uuid": "0ae47b5e-e0ed-47ce-9339-e28edc06ff85", "historyId": "55b8205625d400a7419bce562ec11f0f", "testCaseId": "55b8205625d400a7419bce562ec11f0f", "fullName": "tests.test_get_user_orders.TestGetUserOrders#test_get_user_orders_authorized_user_no_orders", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "DESKTOP-0A7KFK3"}, {"name": "thread", "value": "17096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}