{"name": "Проверка получения количества заказов \"total_today\" для авторизованного пользователя - нет заказов", "status": "failed", "statusDetails": {"message": "AssertionError: Получено неверное значение ключа \"totalToday\": ожидалось \"0\", получено \"144\"", "trace": "self = <test_get_user_orders.TestGetUserOrders object at 0x00000227C0704350>\nsetup_user = ({'email': 'vsfcpnijrc@mail.ru', 'name': 'rrelthmgyo', 'password': 'chbxgbxivs'}, 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6...jljOWVkMjgwMDAxYjNhNjFiZSIsImlhdCI6MTcwNTA3NjM4MCwiZXhwIjoxNzA1MDc3NTgwfQ.WKIL2xJGXsBOuOs-ya1pAEh-Ivwnxs6lYSuwhjP56fM')\n\n    @allure.title('Проверка получения количества заказов \"total_today\" для авторизованного пользователя - нет заказов')\n    def test_get_user_orders_total_today_authorized_user_no_orders(self, setup_user):\n        # сохраняем авторизационный токен пользователя, полученный при регистрации\n        user_data, auth_token = setup_user\n        # получаем заказы пользователя\n        response = u.try_to_get_user_orders(auth_token)\n    \n        # Проверяем, что получен статус-код 200 OK и в теле ответа \"success\" = True\n        # и получаем тело ответа\n        received_body = c.check_success_ok(response)\n        # проверяем поля \"total\" и \"totalToday\" в теле ответа\n>       c.check_received_orders_total_today(received_body, 0)\n\ntests\\test_get_user_orders.py:142: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nhelpers\\helpers_on_check_response.py:218: in check_received_orders_total_today\n    HelpersOnCheck.check_key_and_value_in_body(received_body, KEYS.TOTAL_TODAY_KEY, amount)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse_body = {'orders': [], 'success': True, 'total': 36369, 'totalToday': 144}, key = 'totalToday', value = 0\n\n    @staticmethod\n    @allure.step('Проверяем значение ключа в ответе')\n    def check_key_and_value_in_body(response_body, key, value):\n        # проверяем наличие ключа в ответе\n        assert key in response_body, f'В ответе отсутствует ключ \"{key}\", получен ответ: \"{response_body}\"'\n        # проверяем значение ключа в ответе\n        received_value = response_body[key]\n>       assert received_value == value, f'Получено неверное значение ключа \"{key}\": ожидалось \"{value}\", получено \"{received_value}\"'\nE       AssertionError: Получено неверное значение ключа \"totalToday\": ожидалось \"0\", получено \"144\"\n\nhelpers\\helpers_on_check_response.py:25: AssertionError"}, "steps": [{"name": "Отправляем запрос на получение заказов пользователя", "status": "passed", "steps": [{"name": "Отправляем API-запрос на получение заказов пользователя", "status": "passed", "parameters": [{"name": "headers", "value": "{'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTE2NjljOWVkMjgwMDAxYjNhNjFiZSIsImlhdCI6MTcwNTA3NjM4MCwiZXhwIjoxNzA1MDc3NTgwfQ.WKIL2xJGXsBOuOs-ya1pAEh-Ivwnxs6lYSuwhjP56fM'}"}], "start": 1705076377716, "stop": 1705076379241}], "parameters": [{"name": "auth_token", "value": "'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTE2NjljOWVkMjgwMDAxYjNhNjFiZSIsImlhdCI6MTcwNTA3NjM4MCwiZXhwIjoxNzA1MDc3NTgwfQ.WKIL2xJGXsBOuOs-ya1pAEh-Ivwnxs6lYSuwhjP56fM'"}], "start": 1705076377716, "stop": 1705076379241}, {"name": "Проверяем, что запрос выполнен успешно", "status": "passed", "steps": [{"name": "Проверяем код ответа", "status": "passed", "parameters": [{"name": "response", "value": "<Response [200]>"}, {"name": "expected_code", "value": "200"}], "start": 1705076379241, "stop": 1705076379241}, {"name": "Проверяем значение поля \"success\" в ответе", "status": "passed", "parameters": [{"name": "response", "value": "<Response [200]>"}, {"name": "expected_value", "value": "True"}], "start": 1705076379241, "stop": 1705076379241}], "parameters": [{"name": "response", "value": "<Response [200]>"}], "start": 1705076379241, "stop": 1705076379241}, {"name": "Проверяем в полученном ответе поле \"totalToday\"", "status": "failed", "statusDetails": {"message": "AssertionError: Получено неверное значение ключа \"totalToday\": ожидалось \"0\", получено \"144\"\n", "trace": "  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\helpers\\helpers_on_check_response.py\", line 218, in check_received_orders_total_today\n    HelpersOnCheck.check_key_and_value_in_body(received_body, KEYS.TOTAL_TODAY_KEY, amount)\n  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\helpers\\helpers_on_check_response.py\", line 25, in check_key_and_value_in_body\n    assert received_value == value, f'Получено неверное значение ключа \"{key}\": ожидалось \"{value}\", получено \"{received_value}\"'\n"}, "steps": [{"name": "Проверяем значение ключа в ответе", "status": "failed", "statusDetails": {"message": "AssertionError: Получено неверное значение ключа \"totalToday\": ожидалось \"0\", получено \"144\"\n", "trace": "  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Иван\\PycharmProjects\\qa-python-diplom-2\\helpers\\helpers_on_check_response.py\", line 25, in check_key_and_value_in_body\n    assert received_value == value, f'Получено неверное значение ключа \"{key}\": ожидалось \"{value}\", получено \"{received_value}\"'\n"}, "parameters": [{"name": "response_body", "value": "{'success': True, 'orders': [], 'total': 36369, 'totalToday': 144}"}, {"name": "key", "value": "'totalToday'"}, {"name": "value", "value": "0"}], "start": 1705076379241, "stop": 1705076379241}], "parameters": [{"name": "received_body", "value": "{'success': True, 'orders': [], 'total': 36369, 'totalToday': 144}"}, {"name": "amount", "value": "0"}], "start": 1705076379241, "stop": 1705076379242}], "start": 1705076377716, "stop": 1705076379243, "uuid": "9926790a-4df9-4bf4-a711-6f1a7172f1e5", "historyId": "d1c4fb63054bbb1d0f6836206b0adf8f", "testCaseId": "d1c4fb63054bbb1d0f6836206b0adf8f", "fullName": "tests.test_get_user_orders.TestGetUserOrders#test_get_user_orders_total_today_authorized_user_no_orders", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_ingredients', scope='class')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "DESKTOP-0A7KFK3"}, {"name": "thread", "value": "5180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}